# Ejercicio 1: filtrado y agrupación de datos

Trabajas como analistas para una plataforma de vídeo. Tienes los datos de visualizaciones de la semana. Debes:
1 - Filtrar el DataFrame para mostrar solo las series que tengan entre 15 y 50 millones de visualizaciones.
2 - Agrupar los datos por género, calcular el total de visualizaciones de cada uno y ordenar el resultado de mayor a menor.

In [1]:
datos_streaming = {
    'Título': ['Stranger Things', 'Inception', 'The Crown', 'Avengers', 'Dark', 'Interstellar', 'The Boys'],
    'Tipo': ['Serie', 'Película', 'Serie', 'Película', 'Serie', 'Película', 'Serie'],
    'Género': ['Sci-Fi', 'Sci-Fi', 'Drama', 'Acción', 'Sci-Fi', 'Sci-Fi', 'Acción'],
    'Visualizaciones': [65, 40, 25, 80, 18, 55, 45]
}

In [3]:
import pandas as pd
df_streaming = pd.DataFrame(datos_streaming)

Filtrar series entre 15 y 50 millones de visualizaciones

In [5]:
filtro_series = df_streaming[(df_streaming['Tipo'] == 'Serie') & (df_streaming['Visualizaciones'].between(15, 50))]
display('Series de éxito medio', filtro_series)

'Series de éxito medio'

      Título   Tipo  Género  Visualizaciones
2  The Crown  Serie   Drama               25
4       Dark  Serie  Sci-Fi               18
6   The Boys  Serie  Acción               45

Agrupar por género, calcular el total de visualizaciones y ordenar de mayor a menor

In [10]:
#reset_index() genera la visualización en formato tabla y un dataframe para poder volver a usarlo después
visualizaciones_por_genero = df_streaming.groupby('Género')['Visualizaciones'].sum().reset_index()  
display('Visualizaciones por género', visualizaciones_por_genero)

'Visualizaciones por género'

   Género  Visualizaciones
0  Acción              125
1   Drama               25
2  Sci-Fi              178

Ordenar el resultado de mayor a menor con código

In [11]:
order_desc = visualizaciones_por_genero.sort_values(by='Visualizaciones', ascending=True)
order_desc

   Género  Visualizaciones
1   Drama               25
0  Acción              125
2  Sci-Fi              178