# Limpieza y transformación de datos. 

Trabajamos con BBDD de empleados que tiene valores nulos. Debes:

    1- Rellenar los salarios faltantes NaN con el salario medio de resto de la plantillas
    2- Eliminar las filas donde departamente sea nulo.
    3- Crear una nueva columna Salario_Anual multiplicando el salario mensual por 12

In [4]:
import pandas as pd
import numpy as np

datos_empleados = {
    'Nombre': ['Juan', 'Sara', 'Pedro', 'Laura', 'Mike'],
    'Departamento': ['IT', 'Ventas', np.nan, 'IT', 'Marketing'],
    'Salario_Mensual': [2000, np.nan, 1800, 2500, np.nan]
}

df_empleados = pd.DataFrame(datos_empleados)
df_empleados

  Nombre Departamento  Salario_Mensual
0   Juan           IT           2000.0
1   Sara       Ventas              NaN
2  Pedro          NaN           1800.0
3  Laura           IT           2500.0
4   Mike    Marketing              NaN

1- Rellenar los salarios faltantes np.NaN con el salario medio de resto de la plantillas

In [6]:
media_salarial = df_empleados['Salario_Mensual'].mean()
media_salarial

#para insertar el valor de la media dentro de los campos salario mensual vacíos usamos el método fillna()
df_empleados['Salario_Mensual'] = df_empleados['Salario_Mensual'].fillna(media_salarial)
df_empleados

  Nombre Departamento  Salario_Mensual
0   Juan           IT           2000.0
1   Sara       Ventas           2100.0
2  Pedro          NaN           1800.0
3  Laura           IT           2500.0
4   Mike    Marketing           2100.0